### PR TITLE
🐛 Fix single tilde (`~`) strikethrough parsing

### PR DESCRIPTION
**Pull request by babakks**
This PR fixes microsoft/vscode#146610

### CODE REVIEW

**Comment by babakks** [comment]
@mjbvz Just one thing. I had some problems running the tests since the actual data contained an extra `hc_light` which was missing in the expected results. Now, I'm wondering if we would better change the assertion method `hasThemeChange(d, p)` to look for the keys of `p` within `d` (instead of doing it the other way).

What's your opinion?

**Comment by babakks** [comment]
@mjbvz I don't have access to see the details of the failed checks. Could you please check them?

**Comment by mjbvz** [comment]
Thanks! The test failures look expected. They were caused by our addition of a light high contrast theme. I'll update them shortly

**Comment by babakks** [comment]
@mjbvz If you want, I can make the changes to include HC light in the expected results.

**Pull request merged**
