### PR TITLE
Add source.cpp contentName

### PR DESCRIPTION
**Pull request by alexr00**
This will provide better C++ syntax highlighting within markdown. 
Full context: https://github.com/microsoft/vscode/issues/76603#issuecomment-508575011

### CODE REVIEW

**Comment by mjbvz** [comment]
The main grammar is actually generated using this script: https://github.com/microsoft/vscode-markdown-tm-grammar/blob/master/build.js Could you please look into updating that script too so we don't loose this fix when we next generate the grammar

**Comment by alexr00** [comment]
Yes, will do!

**Comment by alexr00** [comment]
Updated!

**Comment by 5cover** [comment]
Should this be done on the 61 other embedded languages as well? cpp is currently inconsistent with the others, offering both meta.embedded.block.cpp and source.cpp while the 61 other languages support only meta.embedded.block.<language>
I understand this made syntax highlighting better for you, but should it be Markdown's responsibility to provide source.<language> or the theme author's responsibility to support meta.embedded.block.<language> as a parent scope?

**Pull request merged**
