### PR TITLE
json5 markdown support

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Added json5 as an identifier in JSON language, to add support for json5 in markdown

Closes [Microsoft/vscode(#59567)](https://github.com/Microsoft/vscode/issues/59567#issuecomment-427117784)

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks. Yes this looks like the correct change but you need to run the [build script](https://github.com/Microsoft/vscode-markdown-tm-grammar#building) to rebuild the grammar too

**Comment by arshadkazmi42** [comment]
@mjbvz do we need package-lock.json also to be committed in the repo?
I have build and added the build files

**Comment by mjbvz** [comment]
No, since  you have not updated any dependencies you should not commit the package-lock. Please remove it from this change as it is blocking merging this PR

**Comment by arshadkazmi42** [comment]
@mjbvz Done with the change, reverted package.json file to previous commit

**Comment by mjbvz** [comment]
Thanks! Will be in the first VS Code 1.29 insiders build

**Comment by kshetline** [comment]
I'm using the json5 language type, but the syntax coloring I'm getting is just same as for json, so unquoted identifiers are showing up in red, as errors.

image

**Pull request merged**
